### ISSUE TITLE
Dumping Flash of R5F100PF

### ISSUE THREAD

**Issue by riegaz** [JohnDMcMaster/rprl78-src#1]
Hi,

I just started researching a bit about dumping the firmware of a RL78 / R5F100PF to clone it on a blank chip. Could the reading part be done by your software? Did I overlook something?

**Comment by JohnDMcMaster** [comment]
Hi,
This project was created to support security research as part of creating interoperable products. However what you are describing sounds like cloning and is not something I can support.
